/*
  app.js -- This creates an Express webserver with login/register/logout authentication
*/

// *********************************************************** //
//  Loading packages to support the server
// *********************************************************** //
// First we load in all of the packages we need for the server...
const createError = require("http-errors"); // to handle the server errors
const express = require("express");
const path = require("path");  // to refer to local paths
const cookieParser = require("cookie-parser"); // to handle cookies
const session = require("express-session"); // to handle sessions using cookies
const debug = require("debug")("personalapp:server"); 
const layouts = require("express-ejs-layouts");
const axios = require("axios")

// *********************************************************** //
//  Loading models
// *********************************************************** //

const Game = require('./models/Game')
const WishList = require('./models/WishList')

// *********************************************************** //
//  Loading JSON datasets
// *********************************************************** //

// const gameDataSet = require('./Data/games.json')

// *********************************************************** //
//  Connecting to the database
// *********************************************************** //

const mongoose = require( 'mongoose' );

const CONNECTION_URL = 'mongodb+srv://VII:VII666@cluster0.cjsng.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'

mongoose.connect( CONNECTION_URL, { useNewUrlParser: true, useUnifiedTopology: true } );
// fix deprecation warnings
mongoose.set('useFindAndModify', false); 
mongoose.set('useCreateIndex', true);

const db = mongoose.connection;
db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {console.log("we are connected!!!")});


// *********************************************************** //
// Initializing the Express server 
// This code is run once when the app is started and it creates
// a server that respond to requests by sending responses
// *********************************************************** //
const app = express();

// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");


// this allows us to use page layout for the views 
// so we don't have to repeat the headers and footers on every page ...
// the layout is in views/layout.ejs
app.use(layouts);

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling using cookies
app.use(
  session({
    secret: "zzbbyanana789sdfa8f9ds8f90ds87f8d9s789fds", // this ought to be hidden in process.env.SECRET
    resave: false,
    saveUninitialized: false
  })
);

// *********************************************************** //
//  Defining the routes the Fserver will respond to
// *********************************************************** //


// here is the code which handles all /login /signin /logout routes
const auth = require('./routes/auth');
const { deflateSync } = require("zlib");
app.use(auth)

// middleware to test is the user is logged in, and if not, send them to the login page
const isLoggedIn = (req,res,next) => {
  if (res.locals.loggedIn) {
    next()
  }
  else res.redirect('/login')
}

// specify that the server should render the views/index.ejs page for the root path
// and the index.ejs code will be wrapped in the views/layouts.ejs code which provides
// the headers and footers for all webpages generated by this app
app.get("/", (req, res, next) => {
  res.render("index");
});

app.get("/about", (req, res, next) => {
  res.render("about");
});

app.get("/default/:name",
 async (req,res,next) => {
  try{
    const theGame = await Game.find({name:req.params.name})
    res.json(theGame)
  } catch (e){
    next(e);
  }
})

app.get("/default",
 async (req,res,next) => {
  try{
    res.json("")
  } catch (e){
    next(e);
  }
})

/* ************************
  Loading (or reloading) the data into a collection
   ************************ */
// this route loads in the courses into the Game collection
// or updates the games if it is not a new collection

// app.get('/upsertDB_game',
//   async (req,res,next) => {
//     //await Course.deleteMany({})
//     for (AppId in gameDataSet){
//       game = gameDataSet[AppId];
//       const {name,release_date,price,short_description,metacritic_score, recommendations,developers}=game;
//       await Game.findOneAndUpdate({name,release_date,price,short_description,metacritic_score,recommendations,developers},game,{upsert:true})
//     }
//     const num = await Game.find({}).count();
//     res.send("data uploaded: "+num)
//   }
// )

app.post('/games/byName',
  // show list of game in a given name
  async (req,res,next) => {
    const {name} = req.body;
    const reg = new RegExp(name, 'i');
    const games = await Game.find({name:{$regex:reg}}).sort({metacritic_score:-1})
    
    res.locals.games = games
    //res.json(courses)
    res.render('gamelist')
  }
)

app.post('/games/byPrice',
  // show list of game in a given name
  async (req,res,next) => {
    const {price} = req.body;
    const games = await Game.find({price:price}).sort({metacritic_score:-1})
    res.locals.games = games
    //res.json(courses)
    res.render('gamelist')
  }
)

app.post('/games/byDescription',
  // show list of game that contains the given information in its description
  async (req,res,next) => {
    const {description} = req.body;
    const reg = new RegExp(description, 'i');
    const games = await Game.find({short_description:{$regex:reg}}).sort({metacritic_score:-1})
    
    res.locals.games = games
    //res.json(courses)
    res.render('gamelist')
  }
)

app.post('/games/byDeveloper',
  // show list of game of the given developer
  async (req,res,next) => {
    const {developer} = req.body;
    const reg = new RegExp(developer, 'i');
    const games = await Game.find({developers:{$regex:reg}}).sort({metacritic_score:-1})
    res.locals.games = games
    //res.json(courses)
    res.render('gamelist')
  }
)

app.get('/games/show/:gameId',
  // show all info about a course given its gameid
  async (req,res,next) => {
    const {gameId} = req.params;
    const game = await Game.findOne({_id:gameId})
    res.locals.game = game
    //res.json(course)
    res.render('game')
  }
)

app.use(isLoggedIn)

app.get('/addGame/:gameId',
  // add a course to the user's schedule
  async (req,res,next) => {
    try {
      const gameId = req.params.gameId
      const userId = res.locals.user._id
      // check to make sure it's not already loaded
      const lookup = await WishList.find({gameId,userId})
      if (lookup.length==0){
        const wishList = new WishList({gameId,userId})
        await wishList.save()
      }
      res.redirect('/wishList/show')
    } catch(e){
      next(e)
    }
  })

app.get('/wishList/show',
  // show the current user's wish list
  async (req,res,next) => {
    try{
      const userId = res.locals.user._id;
      const gameIds = 
         (await WishList.find({userId}))
                        .sort(x => x.price)
                        .map(x => x.gameId)
      res.locals.games = await Game.find({_id:{$in: gameIds}})
      res.render('wishList')
    } catch(e){
      next(e)
    }
  }
)

app.get('/wishList/remove/:gameId',
  // remove a course from the user's wish list
  async (req,res,next) => {
    try {
      await WishList.remove(
                {userId:res.locals.user._id,
                 gameId:req.params.gameId})
      res.redirect('/wishList/show')

    } catch(e){
      next(e)
    }
  }
)


// here we catch 404 errors and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// this processes any errors generated by the previous routes
// notice that the function has four parameters which is how Express indicates it is an error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render("error");
});


// *********************************************************** //
//  Starting up the server!
// *********************************************************** //
//Here we set the port to use between 1024 and 65535  (2^16-1)
const port = process.env.PORT || "5000";
console.log('connecting on port '+port)
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const { reset } = require("nodemon");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}

function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;
